### ISSUE TITLE
Switching a playback in midstream shows only a black screen (audio works)

### ISSUE THREAD

**Issue by shacharz** [flowplayer/flash#289]
Using Flashls to play m3u8, more details about this issue here. But apparently it's not necessarily related to the Flashls plugin.
https://github.com/mangui/flashls/issues/288

**Comment by danrossi** [comment]
Not an issue I tested with my own HLS implementation and its working fine here. You are replacing the playlist using this method. There is something going on with their method because it's a live stream with no master playlist being used.

**Comment by shacharz** [comment]
By "their" you mean flashls?
There's no master playlist being used because it's not an adaptive bitrate use-case but different 'channels' use-case

**Comment by danrossi** [comment]
There may be playlist fixes in the danmerge branch. I've merged some changes into one there I am delivering to people. It is working with the version I have for any provider used not just hls.

you have no dimensions configured that is what I mean. I believe he picks up the dimensions intensively from the avc but it could be configured from the player dimensions also if none are set.

**Comment by shacharz** [comment]
So are you suggesting I should use the danmerge branch?

**Comment by danrossi** [comment]
$f("player").play({ url: "https://livestream.peer5.com/hls.m3u8" }); this is my test case. I already had a url configured and playing before switching to this. 

I'm planning to get the fixes merged back to dev there are individual pull requests already. I don't believe they are related though. 

I believe the playlist fixes are already in dev though. 

this is the free player build but try this i just built it from my working copy

https://dl.dropboxusercontent.com/u/3394987/flowplayer-3.2.18.zip

**Comment by shacharz** [comment]
Yea or the entire clip properties object, for example in the case of flashls:
$f(0).play({
    accelerated: true,
    url: 'https://livestream.peer5.com/hls.m3u8',
    ipadUrl: 'https://livestream.peer5.com/hls.m3u8',
    urlResolvers: "httpstreaming",
    lang: "fr",
    provider: "httpstreaming",
    autoPlay: true,
    autoBuffering: true
});

**Comment by shacharz** [comment]
Just tested your build,
Besides these errors, because I don't have the associated control file: 
`GET http://localhost:8081/flowplayer/assets/flowplayer.controls-3.2.16.swf 404 (Not Found)`

It doesn't solve the original issue either.

**Comment by danrossi** [comment]
The release file should be fine to use 

http://releases.flowplayer.org/flowplayer.controls/flowplayer.controls-3.2.16.zip

autoBuffering: true turn that off perhaps. It is working with the usual providers.

**Comment by shacharz** [comment]
Thanks, no more 'controls' errors.
But the no video problem is still there.

**Comment by shacharz** [comment]
any updates?
